### ISSUE TITLE
AttributeError: type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by kaaloo** [ramp-kits/autism#24]
Hi,

I used `conda env create -f environment.yml` to install packages, then `source activate autism`.  `ramp_test_submission` works great but `ramp_test_notebook` gives me the following error:

> ----------------------------
> Testing if the notebook can be converted to html
> Testing if the notebook can be executed
> Traceback (most recent call last):
>   File "/home/luis/anaconda3/envs/autism/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/luis/anaconda3/envs/autism/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/luis/anaconda3/envs/autism/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "/home/luis/anaconda3/envs/autism/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
>     app.initialize(argv)
>   File "<decorator-gen-123>", line 2, in initialize
>   File "/home/luis/anaconda3/envs/autism/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "/home/luis/anaconda3/envs/autism/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 452, in initialize
>     zmq_ioloop.install()
>   File "/home/luis/.local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
>     assert (not ioloop.IOLoop.initialized()) or \
> AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by kaaloo** [comment]
Ok `conda install tornado=4.5.3` seems to solve the issue as per https://github.com/jupyter/notebook/issues/3407

**Comment by glemaitre** [comment]
I think that we should solve this in `ramp-workflow`. However, I cannot reproduce:

```
21:57 $ conda env create -f environment.yml
Using Anaconda API: https://api.anaconda.org
Solving environment: \done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.2
  latest version: 4.5.3

Please update conda by running

    $ conda update -n base conda



Downloading and Extracting Packages
tornado 5.0.2####################################################################################################################################################### | 100% 
wheel 0.31.0######################################################################################################################################################## | 100% 
pexpect 4.5.0####################################################################################################################################################### | 100% 
jupyter_client 5.2.3################################################################################################################################################ | 100% 
ipykernel 4.8.2##################################################################################################################################################### | 100% 
certifi 2018.4.16################################################################################################################################################### | 100% 
notebook 5.5.0###################################################################################################################################################### | 100% 
ipython 6.3.1####################################################################################################################################################### | 100% 
setuptools 39.1.0################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master (from -r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
  Downloading https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
     \ 2.8MB 2.8MB/s
Requirement already satisfied: numpy in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Requirement already satisfied: scipy in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Requirement already satisfied: pandas>=0.19.2 in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Requirement already satisfied: scikit-learn>=0.18 in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Collecting cloudpickle (from ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/aa/18/514b557c4d8d4ada1f0454ad06c845454ad438fd5c5e0039ba51d6b032fe/cloudpickle-0.5.2-py2.py3-none-any.whl
Collecting colored (from ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
Requirement already satisfied: python-dateutil>=2 in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from pandas>=0.19.2->ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Requirement already satisfied: pytz>=2011k in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from pandas>=0.19.2->ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Requirement already satisfied: six>=1.5 in /home/lemaitre/miniconda3/envs/autism/lib/python3.6/site-packages (from python-dateutil>=2->pandas>=0.19.2->ramp-workflow==0+unknown->-r /home/lemaitre/Documents/code/research/ramp/autism/condaenv.jqa003r8.requirements.txt (line 1))
Installing collected packages: cloudpickle, colored, ramp-workflow
  Running setup.py install for ramp-workflow ... done
Successfully installed cloudpickle-0.5.2 colored-1.3.5 ramp-workflow-0+unknown
#
# To activate this environment, use:
# > source activate autism
#
# To deactivate an active environment, use:
# > source deactivate
#
22:00 $ source activate autism
(autism) ✔ 
22:01 $ ramp_test_submission 
Testing Autism Spectrum Disorder classification
Reading train and test files from ./data ...
Reading cv ...
Training ./submissions/starting_kit ...
CV fold 0
	score    auc    acc
	train  0.847  0.767
	valid  0.647  0.611
	test   0.765  0.696
CV fold 1
	score    auc    acc
	train  0.842  0.766
	valid  0.662  0.628
	test   0.659  0.478
CV fold 2
	score    auc    acc
	train  0.854  0.786
	valid  0.645  0.615
	test   0.720  0.609
CV fold 3
	score    auc    acc
	train  0.849  0.769
	valid  0.645  0.619
	test   0.758  0.565
CV fold 4
	score    auc    acc
	train  0.852  0.770
	valid  0.650  0.606
	test   0.735  0.652
CV fold 5
	score    auc    acc
	train  0.847  0.776
	valid  0.680  0.642
	test   0.598  0.565
CV fold 6
	score    auc    acc
	train  0.852  0.764
	valid  0.624  0.602
	test   0.773  0.652
CV fold 7
	score    auc    acc
	train  0.854  0.779
	valid  0.662  0.650
	test   0.644  0.478
----------------------------
Mean CV scores
----------------------------
	score             auc             acc
	train   0.85 ± 0.0039  0.772 ± 0.0071
	valid  0.652 ± 0.0155  0.622 ± 0.0161
	test   0.706 ± 0.0605  0.587 ± 0.0753
----------------------------
Bagged scores
----------------------------
	score    auc
	valid  0.651
	test   0.720
```

**Comment by glemaitre** [comment]
@kaaloo Could you put the output of making the three commands without pinning tornado?
