### ISSUE TITLE
cannot download the data

### ISSUE THREAD

**Issue by ruiyuan2099** [ramp-kits/autism#38]
```
python download_data.py  basc122

Downloading the data from https://storage.ramp.studio/autism/basc122.zip ...
Traceback (most recent call last):
  File "download_data.py", line 170, in <module>
    fetch_fmri_time_series(atlas)
  File "download_data.py", line 153, in fetch_fmri_time_series
    _check_integrity_atlas(atlas)
  File "download_data.py", line 106, in _check_integrity_atlas
    _download_fmri_data(atlas)
  File "download_data.py", line 77, in _download_fmri_data
    _check_and_unzip(output_file, atlas, atlas_directory)
  File "download_data.py", line 62, in _check_and_unzip
    raise IOError('The file downloaded was corrupted. Try again '
```
@GaelVaroquaux @agramfort

**Comment by glemaitre** [comment]
Please remove the file in `data/basc122.zip` and the folder `data/basc122` and call again the downloader.

**Comment by ruiyuan2099** [comment]
@glemaitre It seems that I don't even have the folder data/basc122.zip or data/basc122.

**Comment by glemaitre** [comment]
You will have access to it. It is in the autism repository.
However, I see that our server is down right now:

```
python download_data.py basc122
Downloading the data from https://storage.ramp.studio/autism/basc122.zip ...
Traceback (most recent call last):
  File "download_data.py", line 170, in <module>
    fetch_fmri_time_series(atlas)
  File "download_data.py", line 153, in fetch_fmri_time_series
    _check_integrity_atlas(atlas)
  File "download_data.py", line 106, in _check_integrity_atlas
    _download_fmri_data(atlas)
  File "download_data.py", line 75, in _download_fmri_data
    urlretrieve(ARCHIVE[atlas], filename=output_file)
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/lemaitre/miniconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

You might downloaded a portion of the file. I cannot have access right now to the server but we will fix it tomorrow.

**Comment by glemaitre** [comment]
The server is up.
